default_platform(:android)

platform :android do
  desc "Run Unit Test, Lint and Build APK Release for CI/Nightly"
    lane :ci_check do |options|
      api_level = options[:api_level] || ENV["API_LEVEL"] || "36"
      puts "🚀 Starting CI Check for API Level: #{api_level}"

      gradle(
        task: "testDebugUnitTest",
        flags: "--stacktrace --info",
        properties: {
          "API_LEVEL" => api_level
        }
      )

      gradle(
        task: "lintRelease",
        properties: {
          "API_LEVEL" => api_level
        }
      )

      gradle(
        task: "assemble",
        build_type: "Release",
        properties: {
          "android.builder.sdkDownload" => true,
          "API_LEVEL" => api_level
        }
      )
    end

  desc "Build and Ship to Store (Firebase or Play Store)"
    lane :ship do |options|
      target = options[:target_store] || ENV["TARGET_STORE"] || "firebase"

      if target == "firebase"
        deploy_internal
      elsif target == "google_play"
        deploy_internal_playstore
      end
    end

  desc "Build Debug APK and Deploy to Firebase App Distribution"
  private_lane :deploy_internal do
    puts "🚀 Starting Internal Deployment to Firebase..."
    gradle(task: "assemble", build_type: "Debug")
    service_account_json = ENV["FIREBASE_SERVICE_ACCOUNT_JSON"]
    if service_account_json
      service_account_json = service_account_json.gsub(/^'|'$/, '').gsub(/\n|\r|\t/, '')
      service_account_json = service_account_json.gsub('\\n', "\n")
    end
    firebase_app_distribution(
      service_credentials_json_data: service_account_json,
      app: ENV["FIREBASE_APP_ID"],
      groups: ENV["FIREBASE_TESTER_GROUPS"],
      release_notes: "CI/CD Build: " + changelog_from_git_commits(commits_count: 1)
    )
  end

  desc "Build AAB and Deploy to Google Play Internal"
    private_lane :deploy_internal_playstore do
    puts "🚀 Starting Internal Deployment to Google Play..."
    gradle(task: "bundle", build_type: "Release")
    play_store_json = ENV["GOOGLE_PLAY_JSON"]
    if play_store_json
      # Temporary debug info (safe because it doesn't print the whole key)
      puts "🔑 Debug: JSON raw length is #{play_store_json.length}"

      play_store_json = play_store_json.strip.gsub(/^'|'$/, '').gsub(/\n|\r|\t/, '')
      play_store_json = play_store_json.gsub('\\n', "\n")

      puts "🔑 Debug: JSON after cleaning starts with: #{play_store_json[0..10]}"
      puts "🔑 Debug: JSON after cleaning ends with: #{play_store_json[-10..-1]}"
    end
    upload_to_play_store(
      track: 'internal',
      json_key_data: play_store_json,
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
    end
end
