name: Android CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub Repo to server CI
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Config env JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Config Gradle and auto Cache (follow docs.gradle.org)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          # Help cache dependencies downloaded for next build faster
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      # Grant permission for Gradle Wrapper
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # --- UNIT TEST ---
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

      # --- ANDROID LINT ---
      - name: Run Android Lint
        run: ./gradlew lintDebug

      - name: Publish Lint HTML/XML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-lint-report
          path: app/build/reports/lint-results-debug.*

      # Run build
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk