name: Deploy Internal to Google Play
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Describe Version (e.g: 1.0.3)'
        required: true
        default: '1.0.3'
      version_code:
        description: 'Version Code (need increase)'
        required: true
        default: '4'

jobs:
  verify-code:
    uses: ./.github/workflows/reusable-android-verification.yml
    with:
      api-level: 36
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

  upload-playstore:
    needs: verify-code
    uses: ./.github/workflows/reusable-android-distribution.yml
    with:
      target-store: "google_play"
    secrets:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      MY_KEYSTORE_PASSWORD: ${{ secrets.MY_KEYSTORE_PASSWORD }}
      GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}