name: Deploy Internal to Firebase
on:
  schedule:
    # Run on 00:02 AM daily
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  verify-code:
    uses: ./.github/workflows/reusable-android-verification.yml
    with:
      api-level: 36
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

  upload-firebase:
    needs: verify-code
    uses: ./.github/workflows/reusable-android-distribution.yml
    with:
      target-store: "firebase"
      FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
      FIREBASE_TESTER_GROUPS: ${{ vars.FIREBASE_TESTER_GROUPS }}
    secrets:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      MY_KEYSTORE_PASSWORD: ${{ secrets.MY_KEYSTORE_PASSWORD }}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}