name: Main CI (Trigger & Orchestrator)

on:
  push:
    branches: [ "master1" ]
  pull_request:
    branches: [ "master" ]

jobs:
  android-build:
    uses: ./.github/workflows/reusable-android-verification.yml
    with:
      api-level: 36
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}