name: Main CI (Trigger & Orchestrator)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  android-build:
    uses: ./.github/workflows/reusable-android-build.yml
    with:
      api-level: 36
    secrets:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      MY_KEYSTORE_PASSWORD: ${{ secrets.MY_KEYSTORE_PASSWORD }}