name: Nightly Compatibility Check

on:
  schedule:
    # Run on 00:02 AM daily
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  android-ci-matrix:
    strategy:
      matrix:
        api-level: [24, 30, 35, 36]

    uses: ./.github/workflows/reusable-android-verification.yml
    with:
      api-level: ${{ matrix.api-level }}