name: Nightly Compatibility Check

on:
#  schedule:
#    # Run on 00:02 AM daily
#    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  android-ci-matrix:
    strategy:
      matrix:
        api-level: [36]

    uses: ./.github/workflows/reusable-android-verification.yml
    with:
      api-level: ${{ matrix.api-level }}
      run_ui_tests: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      FIREBASE_TEST_LAB_CREDENTIALS: ${{ secrets.FIREBASE_TEST_LAB_CREDENTIALS }}