name: Reusable Verification

on:
  workflow_call:
    inputs:
      api-level:
        required: true
        type: number
    secrets:
      GH_TOKEN:
        required: true

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      API_LEVEL: ${{ inputs.api-level }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Environment (Java, Ruby, Gradle)
        uses: ./.github/actions/setup-android-env

      - name: Run CI Check
        run: bundle exec fastlane android ci_check api_level:${{ inputs.api-level }}