name: Reusable Verification

on:
  workflow_call:
    inputs:
      api-level:
        required: true
        type: number
    secrets:
      GH_TOKEN:
        required: true
      GOOGLE_SERVICES_JSON:
        required: false

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_SERVICES_CONTENT: ${{ secrets.GOOGLE_SERVICES_JSON }}
      API_LEVEL: ${{ inputs.api-level }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Environment (Java, Ruby, Gradle)
        uses: ./.github/actions/setup-android-env

      - name: Run CI Check
        run: bundle exec fastlane android ci_check api_level:${{ inputs.api-level }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report-api-${{ inputs.api-level }}
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report-api-${{ inputs.api-level }}
          path: app/build/reports/lint-results-release.*
